### ISSUE TITLE
Swift 3.0 and Swift Package Manager

### ISSUE THREAD

**Issue by cloutiertyler** [kellanburket/franz#2]
Do you have any plans to update this for Swift 3.0 and conform it to the Swift PM structure? I'd be happy to help.

**Comment by kellanburket** [comment]
Hey--I just saw this now. If you're still interested in jumping on this project that would be awesome.

**Comment by TheArtOfEngineering** [comment]
I would yes, I'll mess about with it tonight if I can get the time. Thanks!

**Comment by kellanburket** [comment]
Great. I'll add you as a contributor.

**Comment by luli-isa** [comment]
any update on this?

**Comment by TheArtOfEngineering** [comment]
Alas, there has not been on my side as I've mostly been working on https://github.com/SwiftOnEdge/Edge, but I'm hopefully going to be able to get to this soon.

**Comment by mfirry** [comment]
any update on this?

**Comment by cloutiertyler** [comment]
Not from me unfortunately. I've been very busy. I'd like to put this on the backlog though. I'll add it to my reminders.

**Comment by mfirry** [comment]
Cool. I wish I could help (though I'm very very new to Swift). 
Is there anywhere one could read about moving projects from pods to `Package.swift`?

**Comment by cloutiertyler** [comment]
Yep! [Here](https://swift.org/package-manager/#conceptual-overview) and [here](https://github.com/apple/swift-package-manager/tree/master/Documentation) are good places to start!
